{% extends 'public_page.twig' %}

{% macro render_ex(exception) %}
    <div>
        <h3>{{ _T("Details") }}</h3>
        <p>
            <strong>{{ _T("Type:") }}</strong>
            {#get_class($exception)#}
        </p>
        <p>
            <strong>{{ _T("Code:") }}</strong>
            {{ exception.getCode() }}
        </p>
        <p>
            <strong>{{ _T("Message:") }}</strong>
            {{ exception.getMessage() }}
        </p>
        <p>
            <strong>{{ _T("File:") }}</strong>
            {{ exception.getFile() }}
        </p>
        <p>
            <strong>{{ _T("Line:") }}</strong>
            {{ exception.getLine() }}
        </p>
    </div>
    <div>
        <h3>{{ _T("Trace") }}</h3>
        <pre>{{ exception.getTraceAsString() }}</pre>
    </div>
    {% if exception.getPrevious() %}
        {% import _self as fivehundred %}
        {{ fivehundred.render_ex(exception.getPrevious()) }}
    {% endif %}
{% endmacro %}

{% block content %}
    <div class="ui container error">
        <div class="ui negative message">
            <h2>{{ _T("Application error") }}</h2>
    {% if login.isLogged() and login.isAdmin() and constant('GALETTE_DISPLAY_ERRORS') == 1 or constant('GALETTE_MODE') == 'DEV' %}
        {% import _self as fivehundred %}
        {{ fivehundred.render_ex(exception) }}
    {% endif %}
        </div>
    </div>
{% endblock %}
